import { decodedToken } from './auth/decodedToken.js';
import { github, githubOAuth } from './auth/githubauth.js';
import { getUserDetails, isAuthenticated } from './auth/isAuthenticated.js';
import { login, loginExt, verifyToken } from './auth/login.js';
import {
  addWebsite,
  addWebsiteOnlyByURL,
  bookmarkResource,
  bulkBookmarkResources,
  deleteAllResources,
  generateUI,
  getAllCategories,
  getAllTags,
  getResourcesBookmarkedByUser,
  getResourcesByCategories,
  getResourcesByTags,
  getResourcesThatMatchDescription,
  getUserBookmarkedResources,
  getUserWebsites,
  getUserWebsitesNotPublic,
  likeAResource,
  refetchImageAndUpdateResource,
  refetchMetaAndUpdateResource,
  rejectResource,
  setPublicAvailability,
  setResourceAvailableForApproval,
  showAllWebsites,
  showIsAvailableForApproval,
  updateResource,
  getAllTagsAndCategories,
  getPaginatedResources
} from './website/websiteSearch.js';

export {
  addWebsite,
  addWebsiteOnlyByURL,
  bookmarkResource,
  bulkBookmarkResources,
  decodedToken,
  deleteAllResources,
  generateUI,
  getAllCategories,
  getAllTags,
  getResourcesBookmarkedByUser,
  getResourcesByCategories,
  getResourcesByTags,
  getResourcesThatMatchDescription,
  getUserBookmarkedResources,
  getUserDetails,
  getUserWebsites,
  getUserWebsitesNotPublic,
  github,
  githubOAuth,
  isAuthenticated,
  likeAResource,
  login,
  loginExt,
  refetchImageAndUpdateResource,
  refetchMetaAndUpdateResource,
  rejectResource,
  setPublicAvailability,
  setResourceAvailableForApproval,
  showAllWebsites,
  showIsAvailableForApproval,
  updateResource,
  verifyToken,
  getAllTagsAndCategories,
  getPaginatedResources
};

