name: Deploy to Azure Container Apps

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: lazyweb-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and push image to ACR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
          context: .
          secrets: |
            "dotenv=${{ github.workspace }}/.env"
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Check if Container App exists and create if not
        run: |
          if az containerapp show --name ${{ env.IMAGE_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query properties.provisioningState -o tsv &>/dev/null; then
            echo "Container App already exists. Will update in next step."
          else
            echo "Container App does not exist. Creating..."
            az containerapp create \
              --name ${{ env.IMAGE_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --environment ${{ secrets.CONTAINER_APP_ENVIRONMENT }} \
              --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
              --registry-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
              --registry-username ${{ secrets.REGISTRY_USERNAME }} \
              --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
              --target-port 4000 \
              --ingress external \
              --cpu 2.5 \
              --memory 5Gi
          fi
      
      - name: Update Azure Container App
        run: |
          az containerapp update \
            --name ${{ env.IMAGE_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
